# Generated by Django 5.0.1 on 2024-02-03 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProcessedFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unprocessed_file_url', models.URLField()),
                ('processed_file_url', models.URLField(blank=True, null=True)),
                ('task_id', models.CharField(max_length=255, unique=True)),
                ('status', models.CharField(choices=[('Read-to-Upload', 'Read-to-Upload'), ('Read-to-Process', 'Read-to-Process'), ('Success', 'Success'), ('Failed', 'Failed'), ('Corrupted', 'Corrupted')], default='Processing', max_length=20)),
            ],
        ),
    ]
